// Code generated by ent, DO NOT EDIT.

package subscriptionwalletledger

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldLTE(FieldID, id))
}

// SubscriptionID applies equality check predicate on the "subscription_id" field. It's identical to SubscriptionIDEQ.
func SubscriptionID(v int64) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldEQ(FieldSubscriptionID, v))
}

// DeltaUsd applies equality check predicate on the "delta_usd" field. It's identical to DeltaUsdEQ.
func DeltaUsd(v float64) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldEQ(FieldDeltaUsd, v))
}

// BalanceAfter applies equality check predicate on the "balance_after" field. It's identical to BalanceAfterEQ.
func BalanceAfter(v float64) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldEQ(FieldBalanceAfter, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldEQ(FieldReason, v))
}

// UsageLogID applies equality check predicate on the "usage_log_id" field. It's identical to UsageLogIDEQ.
func UsageLogID(v int64) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldEQ(FieldUsageLogID, v))
}

// OperatorID applies equality check predicate on the "operator_id" field. It's identical to OperatorIDEQ.
func OperatorID(v int64) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldEQ(FieldOperatorID, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldEQ(FieldNotes, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldEQ(FieldCreatedAt, v))
}

// SubscriptionIDEQ applies the EQ predicate on the "subscription_id" field.
func SubscriptionIDEQ(v int64) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldEQ(FieldSubscriptionID, v))
}

// SubscriptionIDNEQ applies the NEQ predicate on the "subscription_id" field.
func SubscriptionIDNEQ(v int64) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldNEQ(FieldSubscriptionID, v))
}

// SubscriptionIDIn applies the In predicate on the "subscription_id" field.
func SubscriptionIDIn(vs ...int64) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldIn(FieldSubscriptionID, vs...))
}

// SubscriptionIDNotIn applies the NotIn predicate on the "subscription_id" field.
func SubscriptionIDNotIn(vs ...int64) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldNotIn(FieldSubscriptionID, vs...))
}

// DeltaUsdEQ applies the EQ predicate on the "delta_usd" field.
func DeltaUsdEQ(v float64) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldEQ(FieldDeltaUsd, v))
}

// DeltaUsdNEQ applies the NEQ predicate on the "delta_usd" field.
func DeltaUsdNEQ(v float64) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldNEQ(FieldDeltaUsd, v))
}

// DeltaUsdIn applies the In predicate on the "delta_usd" field.
func DeltaUsdIn(vs ...float64) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldIn(FieldDeltaUsd, vs...))
}

// DeltaUsdNotIn applies the NotIn predicate on the "delta_usd" field.
func DeltaUsdNotIn(vs ...float64) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldNotIn(FieldDeltaUsd, vs...))
}

// DeltaUsdGT applies the GT predicate on the "delta_usd" field.
func DeltaUsdGT(v float64) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldGT(FieldDeltaUsd, v))
}

// DeltaUsdGTE applies the GTE predicate on the "delta_usd" field.
func DeltaUsdGTE(v float64) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldGTE(FieldDeltaUsd, v))
}

// DeltaUsdLT applies the LT predicate on the "delta_usd" field.
func DeltaUsdLT(v float64) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldLT(FieldDeltaUsd, v))
}

// DeltaUsdLTE applies the LTE predicate on the "delta_usd" field.
func DeltaUsdLTE(v float64) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldLTE(FieldDeltaUsd, v))
}

// BalanceAfterEQ applies the EQ predicate on the "balance_after" field.
func BalanceAfterEQ(v float64) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldEQ(FieldBalanceAfter, v))
}

// BalanceAfterNEQ applies the NEQ predicate on the "balance_after" field.
func BalanceAfterNEQ(v float64) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldNEQ(FieldBalanceAfter, v))
}

// BalanceAfterIn applies the In predicate on the "balance_after" field.
func BalanceAfterIn(vs ...float64) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldIn(FieldBalanceAfter, vs...))
}

// BalanceAfterNotIn applies the NotIn predicate on the "balance_after" field.
func BalanceAfterNotIn(vs ...float64) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldNotIn(FieldBalanceAfter, vs...))
}

// BalanceAfterGT applies the GT predicate on the "balance_after" field.
func BalanceAfterGT(v float64) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldGT(FieldBalanceAfter, v))
}

// BalanceAfterGTE applies the GTE predicate on the "balance_after" field.
func BalanceAfterGTE(v float64) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldGTE(FieldBalanceAfter, v))
}

// BalanceAfterLT applies the LT predicate on the "balance_after" field.
func BalanceAfterLT(v float64) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldLT(FieldBalanceAfter, v))
}

// BalanceAfterLTE applies the LTE predicate on the "balance_after" field.
func BalanceAfterLTE(v float64) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldLTE(FieldBalanceAfter, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldContainsFold(FieldReason, v))
}

// UsageLogIDEQ applies the EQ predicate on the "usage_log_id" field.
func UsageLogIDEQ(v int64) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldEQ(FieldUsageLogID, v))
}

// UsageLogIDNEQ applies the NEQ predicate on the "usage_log_id" field.
func UsageLogIDNEQ(v int64) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldNEQ(FieldUsageLogID, v))
}

// UsageLogIDIn applies the In predicate on the "usage_log_id" field.
func UsageLogIDIn(vs ...int64) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldIn(FieldUsageLogID, vs...))
}

// UsageLogIDNotIn applies the NotIn predicate on the "usage_log_id" field.
func UsageLogIDNotIn(vs ...int64) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldNotIn(FieldUsageLogID, vs...))
}

// UsageLogIDIsNil applies the IsNil predicate on the "usage_log_id" field.
func UsageLogIDIsNil() predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldIsNull(FieldUsageLogID))
}

// UsageLogIDNotNil applies the NotNil predicate on the "usage_log_id" field.
func UsageLogIDNotNil() predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldNotNull(FieldUsageLogID))
}

// OperatorIDEQ applies the EQ predicate on the "operator_id" field.
func OperatorIDEQ(v int64) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldEQ(FieldOperatorID, v))
}

// OperatorIDNEQ applies the NEQ predicate on the "operator_id" field.
func OperatorIDNEQ(v int64) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldNEQ(FieldOperatorID, v))
}

// OperatorIDIn applies the In predicate on the "operator_id" field.
func OperatorIDIn(vs ...int64) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldIn(FieldOperatorID, vs...))
}

// OperatorIDNotIn applies the NotIn predicate on the "operator_id" field.
func OperatorIDNotIn(vs ...int64) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldNotIn(FieldOperatorID, vs...))
}

// OperatorIDIsNil applies the IsNil predicate on the "operator_id" field.
func OperatorIDIsNil() predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldIsNull(FieldOperatorID))
}

// OperatorIDNotNil applies the NotNil predicate on the "operator_id" field.
func OperatorIDNotNil() predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldNotNull(FieldOperatorID))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldContainsFold(FieldNotes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.FieldLTE(FieldCreatedAt, v))
}

// HasSubscription applies the HasEdge predicate on the "subscription" edge.
func HasSubscription() predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SubscriptionTable, SubscriptionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSubscriptionWith applies the HasEdge predicate on the "subscription" edge with a given conditions (other predicates).
func HasSubscriptionWith(preds ...predicate.UserSubscription) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(func(s *sql.Selector) {
		step := newSubscriptionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUsageLog applies the HasEdge predicate on the "usage_log" edge.
func HasUsageLog() predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UsageLogTable, UsageLogColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsageLogWith applies the HasEdge predicate on the "usage_log" edge with a given conditions (other predicates).
func HasUsageLogWith(preds ...predicate.UsageLog) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(func(s *sql.Selector) {
		step := newUsageLogStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOperator applies the HasEdge predicate on the "operator" edge.
func HasOperator() predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OperatorTable, OperatorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOperatorWith applies the HasEdge predicate on the "operator" edge with a given conditions (other predicates).
func HasOperatorWith(preds ...predicate.User) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(func(s *sql.Selector) {
		step := newOperatorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SubscriptionWalletLedger) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SubscriptionWalletLedger) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SubscriptionWalletLedger) predicate.SubscriptionWalletLedger {
	return predicate.SubscriptionWalletLedger(sql.NotPredicates(p))
}
