// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionwalletledger"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// SubscriptionWalletLedgerUpdate is the builder for updating SubscriptionWalletLedger entities.
type SubscriptionWalletLedgerUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionWalletLedgerMutation
}

// Where appends a list predicates to the SubscriptionWalletLedgerUpdate builder.
func (_u *SubscriptionWalletLedgerUpdate) Where(ps ...predicate.SubscriptionWalletLedger) *SubscriptionWalletLedgerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *SubscriptionWalletLedgerUpdate) SetSubscriptionID(v int64) *SubscriptionWalletLedgerUpdate {
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *SubscriptionWalletLedgerUpdate) SetNillableSubscriptionID(v *int64) *SubscriptionWalletLedgerUpdate {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// SetDeltaUsd sets the "delta_usd" field.
func (_u *SubscriptionWalletLedgerUpdate) SetDeltaUsd(v float64) *SubscriptionWalletLedgerUpdate {
	_u.mutation.ResetDeltaUsd()
	_u.mutation.SetDeltaUsd(v)
	return _u
}

// SetNillableDeltaUsd sets the "delta_usd" field if the given value is not nil.
func (_u *SubscriptionWalletLedgerUpdate) SetNillableDeltaUsd(v *float64) *SubscriptionWalletLedgerUpdate {
	if v != nil {
		_u.SetDeltaUsd(*v)
	}
	return _u
}

// AddDeltaUsd adds value to the "delta_usd" field.
func (_u *SubscriptionWalletLedgerUpdate) AddDeltaUsd(v float64) *SubscriptionWalletLedgerUpdate {
	_u.mutation.AddDeltaUsd(v)
	return _u
}

// SetBalanceAfter sets the "balance_after" field.
func (_u *SubscriptionWalletLedgerUpdate) SetBalanceAfter(v float64) *SubscriptionWalletLedgerUpdate {
	_u.mutation.ResetBalanceAfter()
	_u.mutation.SetBalanceAfter(v)
	return _u
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_u *SubscriptionWalletLedgerUpdate) SetNillableBalanceAfter(v *float64) *SubscriptionWalletLedgerUpdate {
	if v != nil {
		_u.SetBalanceAfter(*v)
	}
	return _u
}

// AddBalanceAfter adds value to the "balance_after" field.
func (_u *SubscriptionWalletLedgerUpdate) AddBalanceAfter(v float64) *SubscriptionWalletLedgerUpdate {
	_u.mutation.AddBalanceAfter(v)
	return _u
}

// SetReason sets the "reason" field.
func (_u *SubscriptionWalletLedgerUpdate) SetReason(v string) *SubscriptionWalletLedgerUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *SubscriptionWalletLedgerUpdate) SetNillableReason(v *string) *SubscriptionWalletLedgerUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetUsageLogID sets the "usage_log_id" field.
func (_u *SubscriptionWalletLedgerUpdate) SetUsageLogID(v int64) *SubscriptionWalletLedgerUpdate {
	_u.mutation.SetUsageLogID(v)
	return _u
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_u *SubscriptionWalletLedgerUpdate) SetNillableUsageLogID(v *int64) *SubscriptionWalletLedgerUpdate {
	if v != nil {
		_u.SetUsageLogID(*v)
	}
	return _u
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (_u *SubscriptionWalletLedgerUpdate) ClearUsageLogID() *SubscriptionWalletLedgerUpdate {
	_u.mutation.ClearUsageLogID()
	return _u
}

// SetOperatorID sets the "operator_id" field.
func (_u *SubscriptionWalletLedgerUpdate) SetOperatorID(v int64) *SubscriptionWalletLedgerUpdate {
	_u.mutation.SetOperatorID(v)
	return _u
}

// SetNillableOperatorID sets the "operator_id" field if the given value is not nil.
func (_u *SubscriptionWalletLedgerUpdate) SetNillableOperatorID(v *int64) *SubscriptionWalletLedgerUpdate {
	if v != nil {
		_u.SetOperatorID(*v)
	}
	return _u
}

// ClearOperatorID clears the value of the "operator_id" field.
func (_u *SubscriptionWalletLedgerUpdate) ClearOperatorID() *SubscriptionWalletLedgerUpdate {
	_u.mutation.ClearOperatorID()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *SubscriptionWalletLedgerUpdate) SetNotes(v string) *SubscriptionWalletLedgerUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *SubscriptionWalletLedgerUpdate) SetNillableNotes(v *string) *SubscriptionWalletLedgerUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *SubscriptionWalletLedgerUpdate) ClearNotes() *SubscriptionWalletLedgerUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetSubscription sets the "subscription" edge to the UserSubscription entity.
func (_u *SubscriptionWalletLedgerUpdate) SetSubscription(v *UserSubscription) *SubscriptionWalletLedgerUpdate {
	return _u.SetSubscriptionID(v.ID)
}

// SetUsageLog sets the "usage_log" edge to the UsageLog entity.
func (_u *SubscriptionWalletLedgerUpdate) SetUsageLog(v *UsageLog) *SubscriptionWalletLedgerUpdate {
	return _u.SetUsageLogID(v.ID)
}

// SetOperator sets the "operator" edge to the User entity.
func (_u *SubscriptionWalletLedgerUpdate) SetOperator(v *User) *SubscriptionWalletLedgerUpdate {
	return _u.SetOperatorID(v.ID)
}

// Mutation returns the SubscriptionWalletLedgerMutation object of the builder.
func (_u *SubscriptionWalletLedgerUpdate) Mutation() *SubscriptionWalletLedgerMutation {
	return _u.mutation
}

// ClearSubscription clears the "subscription" edge to the UserSubscription entity.
func (_u *SubscriptionWalletLedgerUpdate) ClearSubscription() *SubscriptionWalletLedgerUpdate {
	_u.mutation.ClearSubscription()
	return _u
}

// ClearUsageLog clears the "usage_log" edge to the UsageLog entity.
func (_u *SubscriptionWalletLedgerUpdate) ClearUsageLog() *SubscriptionWalletLedgerUpdate {
	_u.mutation.ClearUsageLog()
	return _u
}

// ClearOperator clears the "operator" edge to the User entity.
func (_u *SubscriptionWalletLedgerUpdate) ClearOperator() *SubscriptionWalletLedgerUpdate {
	_u.mutation.ClearOperator()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubscriptionWalletLedgerUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionWalletLedgerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubscriptionWalletLedgerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionWalletLedgerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionWalletLedgerUpdate) check() error {
	if v, ok := _u.mutation.Reason(); ok {
		if err := subscriptionwalletledger.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "SubscriptionWalletLedger.reason": %w`, err)}
		}
	}
	if _u.mutation.SubscriptionCleared() && len(_u.mutation.SubscriptionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionWalletLedger.subscription"`)
	}
	return nil
}

func (_u *SubscriptionWalletLedgerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionwalletledger.Table, subscriptionwalletledger.Columns, sqlgraph.NewFieldSpec(subscriptionwalletledger.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeltaUsd(); ok {
		_spec.SetField(subscriptionwalletledger.FieldDeltaUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDeltaUsd(); ok {
		_spec.AddField(subscriptionwalletledger.FieldDeltaUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceAfter(); ok {
		_spec.SetField(subscriptionwalletledger.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfter(); ok {
		_spec.AddField(subscriptionwalletledger.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(subscriptionwalletledger.FieldReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(subscriptionwalletledger.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(subscriptionwalletledger.FieldNotes, field.TypeString)
	}
	if _u.mutation.SubscriptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionwalletledger.SubscriptionTable,
			Columns: []string{subscriptionwalletledger.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionwalletledger.SubscriptionTable,
			Columns: []string{subscriptionwalletledger.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsageLogCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionwalletledger.UsageLogTable,
			Columns: []string{subscriptionwalletledger.UsageLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionwalletledger.UsageLogTable,
			Columns: []string{subscriptionwalletledger.UsageLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OperatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionwalletledger.OperatorTable,
			Columns: []string{subscriptionwalletledger.OperatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OperatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionwalletledger.OperatorTable,
			Columns: []string{subscriptionwalletledger.OperatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionwalletledger.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubscriptionWalletLedgerUpdateOne is the builder for updating a single SubscriptionWalletLedger entity.
type SubscriptionWalletLedgerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionWalletLedgerMutation
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *SubscriptionWalletLedgerUpdateOne) SetSubscriptionID(v int64) *SubscriptionWalletLedgerUpdateOne {
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *SubscriptionWalletLedgerUpdateOne) SetNillableSubscriptionID(v *int64) *SubscriptionWalletLedgerUpdateOne {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// SetDeltaUsd sets the "delta_usd" field.
func (_u *SubscriptionWalletLedgerUpdateOne) SetDeltaUsd(v float64) *SubscriptionWalletLedgerUpdateOne {
	_u.mutation.ResetDeltaUsd()
	_u.mutation.SetDeltaUsd(v)
	return _u
}

// SetNillableDeltaUsd sets the "delta_usd" field if the given value is not nil.
func (_u *SubscriptionWalletLedgerUpdateOne) SetNillableDeltaUsd(v *float64) *SubscriptionWalletLedgerUpdateOne {
	if v != nil {
		_u.SetDeltaUsd(*v)
	}
	return _u
}

// AddDeltaUsd adds value to the "delta_usd" field.
func (_u *SubscriptionWalletLedgerUpdateOne) AddDeltaUsd(v float64) *SubscriptionWalletLedgerUpdateOne {
	_u.mutation.AddDeltaUsd(v)
	return _u
}

// SetBalanceAfter sets the "balance_after" field.
func (_u *SubscriptionWalletLedgerUpdateOne) SetBalanceAfter(v float64) *SubscriptionWalletLedgerUpdateOne {
	_u.mutation.ResetBalanceAfter()
	_u.mutation.SetBalanceAfter(v)
	return _u
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_u *SubscriptionWalletLedgerUpdateOne) SetNillableBalanceAfter(v *float64) *SubscriptionWalletLedgerUpdateOne {
	if v != nil {
		_u.SetBalanceAfter(*v)
	}
	return _u
}

// AddBalanceAfter adds value to the "balance_after" field.
func (_u *SubscriptionWalletLedgerUpdateOne) AddBalanceAfter(v float64) *SubscriptionWalletLedgerUpdateOne {
	_u.mutation.AddBalanceAfter(v)
	return _u
}

// SetReason sets the "reason" field.
func (_u *SubscriptionWalletLedgerUpdateOne) SetReason(v string) *SubscriptionWalletLedgerUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *SubscriptionWalletLedgerUpdateOne) SetNillableReason(v *string) *SubscriptionWalletLedgerUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetUsageLogID sets the "usage_log_id" field.
func (_u *SubscriptionWalletLedgerUpdateOne) SetUsageLogID(v int64) *SubscriptionWalletLedgerUpdateOne {
	_u.mutation.SetUsageLogID(v)
	return _u
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_u *SubscriptionWalletLedgerUpdateOne) SetNillableUsageLogID(v *int64) *SubscriptionWalletLedgerUpdateOne {
	if v != nil {
		_u.SetUsageLogID(*v)
	}
	return _u
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (_u *SubscriptionWalletLedgerUpdateOne) ClearUsageLogID() *SubscriptionWalletLedgerUpdateOne {
	_u.mutation.ClearUsageLogID()
	return _u
}

// SetOperatorID sets the "operator_id" field.
func (_u *SubscriptionWalletLedgerUpdateOne) SetOperatorID(v int64) *SubscriptionWalletLedgerUpdateOne {
	_u.mutation.SetOperatorID(v)
	return _u
}

// SetNillableOperatorID sets the "operator_id" field if the given value is not nil.
func (_u *SubscriptionWalletLedgerUpdateOne) SetNillableOperatorID(v *int64) *SubscriptionWalletLedgerUpdateOne {
	if v != nil {
		_u.SetOperatorID(*v)
	}
	return _u
}

// ClearOperatorID clears the value of the "operator_id" field.
func (_u *SubscriptionWalletLedgerUpdateOne) ClearOperatorID() *SubscriptionWalletLedgerUpdateOne {
	_u.mutation.ClearOperatorID()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *SubscriptionWalletLedgerUpdateOne) SetNotes(v string) *SubscriptionWalletLedgerUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *SubscriptionWalletLedgerUpdateOne) SetNillableNotes(v *string) *SubscriptionWalletLedgerUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *SubscriptionWalletLedgerUpdateOne) ClearNotes() *SubscriptionWalletLedgerUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetSubscription sets the "subscription" edge to the UserSubscription entity.
func (_u *SubscriptionWalletLedgerUpdateOne) SetSubscription(v *UserSubscription) *SubscriptionWalletLedgerUpdateOne {
	return _u.SetSubscriptionID(v.ID)
}

// SetUsageLog sets the "usage_log" edge to the UsageLog entity.
func (_u *SubscriptionWalletLedgerUpdateOne) SetUsageLog(v *UsageLog) *SubscriptionWalletLedgerUpdateOne {
	return _u.SetUsageLogID(v.ID)
}

// SetOperator sets the "operator" edge to the User entity.
func (_u *SubscriptionWalletLedgerUpdateOne) SetOperator(v *User) *SubscriptionWalletLedgerUpdateOne {
	return _u.SetOperatorID(v.ID)
}

// Mutation returns the SubscriptionWalletLedgerMutation object of the builder.
func (_u *SubscriptionWalletLedgerUpdateOne) Mutation() *SubscriptionWalletLedgerMutation {
	return _u.mutation
}

// ClearSubscription clears the "subscription" edge to the UserSubscription entity.
func (_u *SubscriptionWalletLedgerUpdateOne) ClearSubscription() *SubscriptionWalletLedgerUpdateOne {
	_u.mutation.ClearSubscription()
	return _u
}

// ClearUsageLog clears the "usage_log" edge to the UsageLog entity.
func (_u *SubscriptionWalletLedgerUpdateOne) ClearUsageLog() *SubscriptionWalletLedgerUpdateOne {
	_u.mutation.ClearUsageLog()
	return _u
}

// ClearOperator clears the "operator" edge to the User entity.
func (_u *SubscriptionWalletLedgerUpdateOne) ClearOperator() *SubscriptionWalletLedgerUpdateOne {
	_u.mutation.ClearOperator()
	return _u
}

// Where appends a list predicates to the SubscriptionWalletLedgerUpdate builder.
func (_u *SubscriptionWalletLedgerUpdateOne) Where(ps ...predicate.SubscriptionWalletLedger) *SubscriptionWalletLedgerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubscriptionWalletLedgerUpdateOne) Select(field string, fields ...string) *SubscriptionWalletLedgerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SubscriptionWalletLedger entity.
func (_u *SubscriptionWalletLedgerUpdateOne) Save(ctx context.Context) (*SubscriptionWalletLedger, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionWalletLedgerUpdateOne) SaveX(ctx context.Context) *SubscriptionWalletLedger {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubscriptionWalletLedgerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionWalletLedgerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionWalletLedgerUpdateOne) check() error {
	if v, ok := _u.mutation.Reason(); ok {
		if err := subscriptionwalletledger.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "SubscriptionWalletLedger.reason": %w`, err)}
		}
	}
	if _u.mutation.SubscriptionCleared() && len(_u.mutation.SubscriptionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionWalletLedger.subscription"`)
	}
	return nil
}

func (_u *SubscriptionWalletLedgerUpdateOne) sqlSave(ctx context.Context) (_node *SubscriptionWalletLedger, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionwalletledger.Table, subscriptionwalletledger.Columns, sqlgraph.NewFieldSpec(subscriptionwalletledger.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SubscriptionWalletLedger.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptionwalletledger.FieldID)
		for _, f := range fields {
			if !subscriptionwalletledger.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscriptionwalletledger.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeltaUsd(); ok {
		_spec.SetField(subscriptionwalletledger.FieldDeltaUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDeltaUsd(); ok {
		_spec.AddField(subscriptionwalletledger.FieldDeltaUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceAfter(); ok {
		_spec.SetField(subscriptionwalletledger.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfter(); ok {
		_spec.AddField(subscriptionwalletledger.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(subscriptionwalletledger.FieldReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(subscriptionwalletledger.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(subscriptionwalletledger.FieldNotes, field.TypeString)
	}
	if _u.mutation.SubscriptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionwalletledger.SubscriptionTable,
			Columns: []string{subscriptionwalletledger.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionwalletledger.SubscriptionTable,
			Columns: []string{subscriptionwalletledger.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsageLogCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionwalletledger.UsageLogTable,
			Columns: []string{subscriptionwalletledger.UsageLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionwalletledger.UsageLogTable,
			Columns: []string{subscriptionwalletledger.UsageLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OperatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionwalletledger.OperatorTable,
			Columns: []string{subscriptionwalletledger.OperatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OperatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionwalletledger.OperatorTable,
			Columns: []string{subscriptionwalletledger.OperatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SubscriptionWalletLedger{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionwalletledger.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
