// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionwalletledger"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// SubscriptionWalletLedger is the model entity for the SubscriptionWalletLedger schema.
type SubscriptionWalletLedger struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// SubscriptionID holds the value of the "subscription_id" field.
	SubscriptionID int64 `json:"subscription_id,omitempty"`
	// 正=入账（激活/退款）, 负=出账（消费）
	DeltaUsd float64 `json:"delta_usd,omitempty"`
	// 此次操作后余额（冗余，便于排查）
	BalanceAfter float64 `json:"balance_after,omitempty"`
	// activation | usage | refund | adjustment | expiration
	Reason string `json:"reason,omitempty"`
	// 仅 reason=usage 时填，关联到 usage_logs.id
	UsageLogID *int64 `json:"usage_log_id,omitempty"`
	// 仅 refund/adjustment 时填，操作员 user_id
	OperatorID *int64 `json:"operator_id,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes *string `json:"notes,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SubscriptionWalletLedgerQuery when eager-loading is set.
	Edges        SubscriptionWalletLedgerEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SubscriptionWalletLedgerEdges holds the relations/edges for other nodes in the graph.
type SubscriptionWalletLedgerEdges struct {
	// Subscription holds the value of the subscription edge.
	Subscription *UserSubscription `json:"subscription,omitempty"`
	// UsageLog holds the value of the usage_log edge.
	UsageLog *UsageLog `json:"usage_log,omitempty"`
	// Operator holds the value of the operator edge.
	Operator *User `json:"operator,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// SubscriptionOrErr returns the Subscription value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionWalletLedgerEdges) SubscriptionOrErr() (*UserSubscription, error) {
	if e.Subscription != nil {
		return e.Subscription, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: usersubscription.Label}
	}
	return nil, &NotLoadedError{edge: "subscription"}
}

// UsageLogOrErr returns the UsageLog value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionWalletLedgerEdges) UsageLogOrErr() (*UsageLog, error) {
	if e.UsageLog != nil {
		return e.UsageLog, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: usagelog.Label}
	}
	return nil, &NotLoadedError{edge: "usage_log"}
}

// OperatorOrErr returns the Operator value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionWalletLedgerEdges) OperatorOrErr() (*User, error) {
	if e.Operator != nil {
		return e.Operator, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "operator"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SubscriptionWalletLedger) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case subscriptionwalletledger.FieldDeltaUsd, subscriptionwalletledger.FieldBalanceAfter:
			values[i] = new(sql.NullFloat64)
		case subscriptionwalletledger.FieldID, subscriptionwalletledger.FieldSubscriptionID, subscriptionwalletledger.FieldUsageLogID, subscriptionwalletledger.FieldOperatorID:
			values[i] = new(sql.NullInt64)
		case subscriptionwalletledger.FieldReason, subscriptionwalletledger.FieldNotes:
			values[i] = new(sql.NullString)
		case subscriptionwalletledger.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SubscriptionWalletLedger fields.
func (_m *SubscriptionWalletLedger) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case subscriptionwalletledger.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case subscriptionwalletledger.FieldSubscriptionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_id", values[i])
			} else if value.Valid {
				_m.SubscriptionID = value.Int64
			}
		case subscriptionwalletledger.FieldDeltaUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field delta_usd", values[i])
			} else if value.Valid {
				_m.DeltaUsd = value.Float64
			}
		case subscriptionwalletledger.FieldBalanceAfter:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance_after", values[i])
			} else if value.Valid {
				_m.BalanceAfter = value.Float64
			}
		case subscriptionwalletledger.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = value.String
			}
		case subscriptionwalletledger.FieldUsageLogID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field usage_log_id", values[i])
			} else if value.Valid {
				_m.UsageLogID = new(int64)
				*_m.UsageLogID = value.Int64
			}
		case subscriptionwalletledger.FieldOperatorID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field operator_id", values[i])
			} else if value.Valid {
				_m.OperatorID = new(int64)
				*_m.OperatorID = value.Int64
			}
		case subscriptionwalletledger.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = new(string)
				*_m.Notes = value.String
			}
		case subscriptionwalletledger.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SubscriptionWalletLedger.
// This includes values selected through modifiers, order, etc.
func (_m *SubscriptionWalletLedger) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySubscription queries the "subscription" edge of the SubscriptionWalletLedger entity.
func (_m *SubscriptionWalletLedger) QuerySubscription() *UserSubscriptionQuery {
	return NewSubscriptionWalletLedgerClient(_m.config).QuerySubscription(_m)
}

// QueryUsageLog queries the "usage_log" edge of the SubscriptionWalletLedger entity.
func (_m *SubscriptionWalletLedger) QueryUsageLog() *UsageLogQuery {
	return NewSubscriptionWalletLedgerClient(_m.config).QueryUsageLog(_m)
}

// QueryOperator queries the "operator" edge of the SubscriptionWalletLedger entity.
func (_m *SubscriptionWalletLedger) QueryOperator() *UserQuery {
	return NewSubscriptionWalletLedgerClient(_m.config).QueryOperator(_m)
}

// Update returns a builder for updating this SubscriptionWalletLedger.
// Note that you need to call SubscriptionWalletLedger.Unwrap() before calling this method if this SubscriptionWalletLedger
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SubscriptionWalletLedger) Update() *SubscriptionWalletLedgerUpdateOne {
	return NewSubscriptionWalletLedgerClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SubscriptionWalletLedger entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SubscriptionWalletLedger) Unwrap() *SubscriptionWalletLedger {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SubscriptionWalletLedger is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SubscriptionWalletLedger) String() string {
	var builder strings.Builder
	builder.WriteString("SubscriptionWalletLedger(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("subscription_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SubscriptionID))
	builder.WriteString(", ")
	builder.WriteString("delta_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeltaUsd))
	builder.WriteString(", ")
	builder.WriteString("balance_after=")
	builder.WriteString(fmt.Sprintf("%v", _m.BalanceAfter))
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(_m.Reason)
	builder.WriteString(", ")
	if v := _m.UsageLogID; v != nil {
		builder.WriteString("usage_log_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.OperatorID; v != nil {
		builder.WriteString("operator_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Notes; v != nil {
		builder.WriteString("notes=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SubscriptionWalletLedgers is a parsable slice of SubscriptionWalletLedger.
type SubscriptionWalletLedgers []*SubscriptionWalletLedger
