// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionwalletledger"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// SubscriptionWalletLedgerCreate is the builder for creating a SubscriptionWalletLedger entity.
type SubscriptionWalletLedgerCreate struct {
	config
	mutation *SubscriptionWalletLedgerMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetSubscriptionID sets the "subscription_id" field.
func (_c *SubscriptionWalletLedgerCreate) SetSubscriptionID(v int64) *SubscriptionWalletLedgerCreate {
	_c.mutation.SetSubscriptionID(v)
	return _c
}

// SetDeltaUsd sets the "delta_usd" field.
func (_c *SubscriptionWalletLedgerCreate) SetDeltaUsd(v float64) *SubscriptionWalletLedgerCreate {
	_c.mutation.SetDeltaUsd(v)
	return _c
}

// SetBalanceAfter sets the "balance_after" field.
func (_c *SubscriptionWalletLedgerCreate) SetBalanceAfter(v float64) *SubscriptionWalletLedgerCreate {
	_c.mutation.SetBalanceAfter(v)
	return _c
}

// SetReason sets the "reason" field.
func (_c *SubscriptionWalletLedgerCreate) SetReason(v string) *SubscriptionWalletLedgerCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetUsageLogID sets the "usage_log_id" field.
func (_c *SubscriptionWalletLedgerCreate) SetUsageLogID(v int64) *SubscriptionWalletLedgerCreate {
	_c.mutation.SetUsageLogID(v)
	return _c
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_c *SubscriptionWalletLedgerCreate) SetNillableUsageLogID(v *int64) *SubscriptionWalletLedgerCreate {
	if v != nil {
		_c.SetUsageLogID(*v)
	}
	return _c
}

// SetOperatorID sets the "operator_id" field.
func (_c *SubscriptionWalletLedgerCreate) SetOperatorID(v int64) *SubscriptionWalletLedgerCreate {
	_c.mutation.SetOperatorID(v)
	return _c
}

// SetNillableOperatorID sets the "operator_id" field if the given value is not nil.
func (_c *SubscriptionWalletLedgerCreate) SetNillableOperatorID(v *int64) *SubscriptionWalletLedgerCreate {
	if v != nil {
		_c.SetOperatorID(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *SubscriptionWalletLedgerCreate) SetNotes(v string) *SubscriptionWalletLedgerCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *SubscriptionWalletLedgerCreate) SetNillableNotes(v *string) *SubscriptionWalletLedgerCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SubscriptionWalletLedgerCreate) SetCreatedAt(v time.Time) *SubscriptionWalletLedgerCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SubscriptionWalletLedgerCreate) SetNillableCreatedAt(v *time.Time) *SubscriptionWalletLedgerCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetSubscription sets the "subscription" edge to the UserSubscription entity.
func (_c *SubscriptionWalletLedgerCreate) SetSubscription(v *UserSubscription) *SubscriptionWalletLedgerCreate {
	return _c.SetSubscriptionID(v.ID)
}

// SetUsageLog sets the "usage_log" edge to the UsageLog entity.
func (_c *SubscriptionWalletLedgerCreate) SetUsageLog(v *UsageLog) *SubscriptionWalletLedgerCreate {
	return _c.SetUsageLogID(v.ID)
}

// SetOperator sets the "operator" edge to the User entity.
func (_c *SubscriptionWalletLedgerCreate) SetOperator(v *User) *SubscriptionWalletLedgerCreate {
	return _c.SetOperatorID(v.ID)
}

// Mutation returns the SubscriptionWalletLedgerMutation object of the builder.
func (_c *SubscriptionWalletLedgerCreate) Mutation() *SubscriptionWalletLedgerMutation {
	return _c.mutation
}

// Save creates the SubscriptionWalletLedger in the database.
func (_c *SubscriptionWalletLedgerCreate) Save(ctx context.Context) (*SubscriptionWalletLedger, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SubscriptionWalletLedgerCreate) SaveX(ctx context.Context) *SubscriptionWalletLedger {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionWalletLedgerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionWalletLedgerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SubscriptionWalletLedgerCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := subscriptionwalletledger.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SubscriptionWalletLedgerCreate) check() error {
	if _, ok := _c.mutation.SubscriptionID(); !ok {
		return &ValidationError{Name: "subscription_id", err: errors.New(`ent: missing required field "SubscriptionWalletLedger.subscription_id"`)}
	}
	if _, ok := _c.mutation.DeltaUsd(); !ok {
		return &ValidationError{Name: "delta_usd", err: errors.New(`ent: missing required field "SubscriptionWalletLedger.delta_usd"`)}
	}
	if _, ok := _c.mutation.BalanceAfter(); !ok {
		return &ValidationError{Name: "balance_after", err: errors.New(`ent: missing required field "SubscriptionWalletLedger.balance_after"`)}
	}
	if _, ok := _c.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "SubscriptionWalletLedger.reason"`)}
	}
	if v, ok := _c.mutation.Reason(); ok {
		if err := subscriptionwalletledger.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "SubscriptionWalletLedger.reason": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SubscriptionWalletLedger.created_at"`)}
	}
	if len(_c.mutation.SubscriptionIDs()) == 0 {
		return &ValidationError{Name: "subscription", err: errors.New(`ent: missing required edge "SubscriptionWalletLedger.subscription"`)}
	}
	return nil
}

func (_c *SubscriptionWalletLedgerCreate) sqlSave(ctx context.Context) (*SubscriptionWalletLedger, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SubscriptionWalletLedgerCreate) createSpec() (*SubscriptionWalletLedger, *sqlgraph.CreateSpec) {
	var (
		_node = &SubscriptionWalletLedger{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(subscriptionwalletledger.Table, sqlgraph.NewFieldSpec(subscriptionwalletledger.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.DeltaUsd(); ok {
		_spec.SetField(subscriptionwalletledger.FieldDeltaUsd, field.TypeFloat64, value)
		_node.DeltaUsd = value
	}
	if value, ok := _c.mutation.BalanceAfter(); ok {
		_spec.SetField(subscriptionwalletledger.FieldBalanceAfter, field.TypeFloat64, value)
		_node.BalanceAfter = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(subscriptionwalletledger.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(subscriptionwalletledger.FieldNotes, field.TypeString, value)
		_node.Notes = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(subscriptionwalletledger.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionwalletledger.SubscriptionTable,
			Columns: []string{subscriptionwalletledger.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SubscriptionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UsageLogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionwalletledger.UsageLogTable,
			Columns: []string{subscriptionwalletledger.UsageLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UsageLogID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OperatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionwalletledger.OperatorTable,
			Columns: []string{subscriptionwalletledger.OperatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OperatorID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionWalletLedger.Create().
//		SetSubscriptionID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionWalletLedgerUpsert) {
//			SetSubscriptionID(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionWalletLedgerCreate) OnConflict(opts ...sql.ConflictOption) *SubscriptionWalletLedgerUpsertOne {
	_c.conflict = opts
	return &SubscriptionWalletLedgerUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionWalletLedger.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionWalletLedgerCreate) OnConflictColumns(columns ...string) *SubscriptionWalletLedgerUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionWalletLedgerUpsertOne{
		create: _c,
	}
}

type (
	// SubscriptionWalletLedgerUpsertOne is the builder for "upsert"-ing
	//  one SubscriptionWalletLedger node.
	SubscriptionWalletLedgerUpsertOne struct {
		create *SubscriptionWalletLedgerCreate
	}

	// SubscriptionWalletLedgerUpsert is the "OnConflict" setter.
	SubscriptionWalletLedgerUpsert struct {
		*sql.UpdateSet
	}
)

// SetSubscriptionID sets the "subscription_id" field.
func (u *SubscriptionWalletLedgerUpsert) SetSubscriptionID(v int64) *SubscriptionWalletLedgerUpsert {
	u.Set(subscriptionwalletledger.FieldSubscriptionID, v)
	return u
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *SubscriptionWalletLedgerUpsert) UpdateSubscriptionID() *SubscriptionWalletLedgerUpsert {
	u.SetExcluded(subscriptionwalletledger.FieldSubscriptionID)
	return u
}

// SetDeltaUsd sets the "delta_usd" field.
func (u *SubscriptionWalletLedgerUpsert) SetDeltaUsd(v float64) *SubscriptionWalletLedgerUpsert {
	u.Set(subscriptionwalletledger.FieldDeltaUsd, v)
	return u
}

// UpdateDeltaUsd sets the "delta_usd" field to the value that was provided on create.
func (u *SubscriptionWalletLedgerUpsert) UpdateDeltaUsd() *SubscriptionWalletLedgerUpsert {
	u.SetExcluded(subscriptionwalletledger.FieldDeltaUsd)
	return u
}

// AddDeltaUsd adds v to the "delta_usd" field.
func (u *SubscriptionWalletLedgerUpsert) AddDeltaUsd(v float64) *SubscriptionWalletLedgerUpsert {
	u.Add(subscriptionwalletledger.FieldDeltaUsd, v)
	return u
}

// SetBalanceAfter sets the "balance_after" field.
func (u *SubscriptionWalletLedgerUpsert) SetBalanceAfter(v float64) *SubscriptionWalletLedgerUpsert {
	u.Set(subscriptionwalletledger.FieldBalanceAfter, v)
	return u
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *SubscriptionWalletLedgerUpsert) UpdateBalanceAfter() *SubscriptionWalletLedgerUpsert {
	u.SetExcluded(subscriptionwalletledger.FieldBalanceAfter)
	return u
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *SubscriptionWalletLedgerUpsert) AddBalanceAfter(v float64) *SubscriptionWalletLedgerUpsert {
	u.Add(subscriptionwalletledger.FieldBalanceAfter, v)
	return u
}

// SetReason sets the "reason" field.
func (u *SubscriptionWalletLedgerUpsert) SetReason(v string) *SubscriptionWalletLedgerUpsert {
	u.Set(subscriptionwalletledger.FieldReason, v)
	return u
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *SubscriptionWalletLedgerUpsert) UpdateReason() *SubscriptionWalletLedgerUpsert {
	u.SetExcluded(subscriptionwalletledger.FieldReason)
	return u
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *SubscriptionWalletLedgerUpsert) SetUsageLogID(v int64) *SubscriptionWalletLedgerUpsert {
	u.Set(subscriptionwalletledger.FieldUsageLogID, v)
	return u
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *SubscriptionWalletLedgerUpsert) UpdateUsageLogID() *SubscriptionWalletLedgerUpsert {
	u.SetExcluded(subscriptionwalletledger.FieldUsageLogID)
	return u
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (u *SubscriptionWalletLedgerUpsert) ClearUsageLogID() *SubscriptionWalletLedgerUpsert {
	u.SetNull(subscriptionwalletledger.FieldUsageLogID)
	return u
}

// SetOperatorID sets the "operator_id" field.
func (u *SubscriptionWalletLedgerUpsert) SetOperatorID(v int64) *SubscriptionWalletLedgerUpsert {
	u.Set(subscriptionwalletledger.FieldOperatorID, v)
	return u
}

// UpdateOperatorID sets the "operator_id" field to the value that was provided on create.
func (u *SubscriptionWalletLedgerUpsert) UpdateOperatorID() *SubscriptionWalletLedgerUpsert {
	u.SetExcluded(subscriptionwalletledger.FieldOperatorID)
	return u
}

// ClearOperatorID clears the value of the "operator_id" field.
func (u *SubscriptionWalletLedgerUpsert) ClearOperatorID() *SubscriptionWalletLedgerUpsert {
	u.SetNull(subscriptionwalletledger.FieldOperatorID)
	return u
}

// SetNotes sets the "notes" field.
func (u *SubscriptionWalletLedgerUpsert) SetNotes(v string) *SubscriptionWalletLedgerUpsert {
	u.Set(subscriptionwalletledger.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *SubscriptionWalletLedgerUpsert) UpdateNotes() *SubscriptionWalletLedgerUpsert {
	u.SetExcluded(subscriptionwalletledger.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *SubscriptionWalletLedgerUpsert) ClearNotes() *SubscriptionWalletLedgerUpsert {
	u.SetNull(subscriptionwalletledger.FieldNotes)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SubscriptionWalletLedger.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionWalletLedgerUpsertOne) UpdateNewValues() *SubscriptionWalletLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(subscriptionwalletledger.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionWalletLedger.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SubscriptionWalletLedgerUpsertOne) Ignore() *SubscriptionWalletLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionWalletLedgerUpsertOne) DoNothing() *SubscriptionWalletLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionWalletLedgerCreate.OnConflict
// documentation for more info.
func (u *SubscriptionWalletLedgerUpsertOne) Update(set func(*SubscriptionWalletLedgerUpsert)) *SubscriptionWalletLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionWalletLedgerUpsert{UpdateSet: update})
	}))
	return u
}

// SetSubscriptionID sets the "subscription_id" field.
func (u *SubscriptionWalletLedgerUpsertOne) SetSubscriptionID(v int64) *SubscriptionWalletLedgerUpsertOne {
	return u.Update(func(s *SubscriptionWalletLedgerUpsert) {
		s.SetSubscriptionID(v)
	})
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *SubscriptionWalletLedgerUpsertOne) UpdateSubscriptionID() *SubscriptionWalletLedgerUpsertOne {
	return u.Update(func(s *SubscriptionWalletLedgerUpsert) {
		s.UpdateSubscriptionID()
	})
}

// SetDeltaUsd sets the "delta_usd" field.
func (u *SubscriptionWalletLedgerUpsertOne) SetDeltaUsd(v float64) *SubscriptionWalletLedgerUpsertOne {
	return u.Update(func(s *SubscriptionWalletLedgerUpsert) {
		s.SetDeltaUsd(v)
	})
}

// AddDeltaUsd adds v to the "delta_usd" field.
func (u *SubscriptionWalletLedgerUpsertOne) AddDeltaUsd(v float64) *SubscriptionWalletLedgerUpsertOne {
	return u.Update(func(s *SubscriptionWalletLedgerUpsert) {
		s.AddDeltaUsd(v)
	})
}

// UpdateDeltaUsd sets the "delta_usd" field to the value that was provided on create.
func (u *SubscriptionWalletLedgerUpsertOne) UpdateDeltaUsd() *SubscriptionWalletLedgerUpsertOne {
	return u.Update(func(s *SubscriptionWalletLedgerUpsert) {
		s.UpdateDeltaUsd()
	})
}

// SetBalanceAfter sets the "balance_after" field.
func (u *SubscriptionWalletLedgerUpsertOne) SetBalanceAfter(v float64) *SubscriptionWalletLedgerUpsertOne {
	return u.Update(func(s *SubscriptionWalletLedgerUpsert) {
		s.SetBalanceAfter(v)
	})
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *SubscriptionWalletLedgerUpsertOne) AddBalanceAfter(v float64) *SubscriptionWalletLedgerUpsertOne {
	return u.Update(func(s *SubscriptionWalletLedgerUpsert) {
		s.AddBalanceAfter(v)
	})
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *SubscriptionWalletLedgerUpsertOne) UpdateBalanceAfter() *SubscriptionWalletLedgerUpsertOne {
	return u.Update(func(s *SubscriptionWalletLedgerUpsert) {
		s.UpdateBalanceAfter()
	})
}

// SetReason sets the "reason" field.
func (u *SubscriptionWalletLedgerUpsertOne) SetReason(v string) *SubscriptionWalletLedgerUpsertOne {
	return u.Update(func(s *SubscriptionWalletLedgerUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *SubscriptionWalletLedgerUpsertOne) UpdateReason() *SubscriptionWalletLedgerUpsertOne {
	return u.Update(func(s *SubscriptionWalletLedgerUpsert) {
		s.UpdateReason()
	})
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *SubscriptionWalletLedgerUpsertOne) SetUsageLogID(v int64) *SubscriptionWalletLedgerUpsertOne {
	return u.Update(func(s *SubscriptionWalletLedgerUpsert) {
		s.SetUsageLogID(v)
	})
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *SubscriptionWalletLedgerUpsertOne) UpdateUsageLogID() *SubscriptionWalletLedgerUpsertOne {
	return u.Update(func(s *SubscriptionWalletLedgerUpsert) {
		s.UpdateUsageLogID()
	})
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (u *SubscriptionWalletLedgerUpsertOne) ClearUsageLogID() *SubscriptionWalletLedgerUpsertOne {
	return u.Update(func(s *SubscriptionWalletLedgerUpsert) {
		s.ClearUsageLogID()
	})
}

// SetOperatorID sets the "operator_id" field.
func (u *SubscriptionWalletLedgerUpsertOne) SetOperatorID(v int64) *SubscriptionWalletLedgerUpsertOne {
	return u.Update(func(s *SubscriptionWalletLedgerUpsert) {
		s.SetOperatorID(v)
	})
}

// UpdateOperatorID sets the "operator_id" field to the value that was provided on create.
func (u *SubscriptionWalletLedgerUpsertOne) UpdateOperatorID() *SubscriptionWalletLedgerUpsertOne {
	return u.Update(func(s *SubscriptionWalletLedgerUpsert) {
		s.UpdateOperatorID()
	})
}

// ClearOperatorID clears the value of the "operator_id" field.
func (u *SubscriptionWalletLedgerUpsertOne) ClearOperatorID() *SubscriptionWalletLedgerUpsertOne {
	return u.Update(func(s *SubscriptionWalletLedgerUpsert) {
		s.ClearOperatorID()
	})
}

// SetNotes sets the "notes" field.
func (u *SubscriptionWalletLedgerUpsertOne) SetNotes(v string) *SubscriptionWalletLedgerUpsertOne {
	return u.Update(func(s *SubscriptionWalletLedgerUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *SubscriptionWalletLedgerUpsertOne) UpdateNotes() *SubscriptionWalletLedgerUpsertOne {
	return u.Update(func(s *SubscriptionWalletLedgerUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *SubscriptionWalletLedgerUpsertOne) ClearNotes() *SubscriptionWalletLedgerUpsertOne {
	return u.Update(func(s *SubscriptionWalletLedgerUpsert) {
		s.ClearNotes()
	})
}

// Exec executes the query.
func (u *SubscriptionWalletLedgerUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionWalletLedgerCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionWalletLedgerUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SubscriptionWalletLedgerUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SubscriptionWalletLedgerUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SubscriptionWalletLedgerCreateBulk is the builder for creating many SubscriptionWalletLedger entities in bulk.
type SubscriptionWalletLedgerCreateBulk struct {
	config
	err      error
	builders []*SubscriptionWalletLedgerCreate
	conflict []sql.ConflictOption
}

// Save creates the SubscriptionWalletLedger entities in the database.
func (_c *SubscriptionWalletLedgerCreateBulk) Save(ctx context.Context) ([]*SubscriptionWalletLedger, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SubscriptionWalletLedger, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubscriptionWalletLedgerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SubscriptionWalletLedgerCreateBulk) SaveX(ctx context.Context) []*SubscriptionWalletLedger {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionWalletLedgerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionWalletLedgerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionWalletLedger.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionWalletLedgerUpsert) {
//			SetSubscriptionID(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionWalletLedgerCreateBulk) OnConflict(opts ...sql.ConflictOption) *SubscriptionWalletLedgerUpsertBulk {
	_c.conflict = opts
	return &SubscriptionWalletLedgerUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionWalletLedger.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionWalletLedgerCreateBulk) OnConflictColumns(columns ...string) *SubscriptionWalletLedgerUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionWalletLedgerUpsertBulk{
		create: _c,
	}
}

// SubscriptionWalletLedgerUpsertBulk is the builder for "upsert"-ing
// a bulk of SubscriptionWalletLedger nodes.
type SubscriptionWalletLedgerUpsertBulk struct {
	create *SubscriptionWalletLedgerCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SubscriptionWalletLedger.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionWalletLedgerUpsertBulk) UpdateNewValues() *SubscriptionWalletLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(subscriptionwalletledger.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionWalletLedger.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SubscriptionWalletLedgerUpsertBulk) Ignore() *SubscriptionWalletLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionWalletLedgerUpsertBulk) DoNothing() *SubscriptionWalletLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionWalletLedgerCreateBulk.OnConflict
// documentation for more info.
func (u *SubscriptionWalletLedgerUpsertBulk) Update(set func(*SubscriptionWalletLedgerUpsert)) *SubscriptionWalletLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionWalletLedgerUpsert{UpdateSet: update})
	}))
	return u
}

// SetSubscriptionID sets the "subscription_id" field.
func (u *SubscriptionWalletLedgerUpsertBulk) SetSubscriptionID(v int64) *SubscriptionWalletLedgerUpsertBulk {
	return u.Update(func(s *SubscriptionWalletLedgerUpsert) {
		s.SetSubscriptionID(v)
	})
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *SubscriptionWalletLedgerUpsertBulk) UpdateSubscriptionID() *SubscriptionWalletLedgerUpsertBulk {
	return u.Update(func(s *SubscriptionWalletLedgerUpsert) {
		s.UpdateSubscriptionID()
	})
}

// SetDeltaUsd sets the "delta_usd" field.
func (u *SubscriptionWalletLedgerUpsertBulk) SetDeltaUsd(v float64) *SubscriptionWalletLedgerUpsertBulk {
	return u.Update(func(s *SubscriptionWalletLedgerUpsert) {
		s.SetDeltaUsd(v)
	})
}

// AddDeltaUsd adds v to the "delta_usd" field.
func (u *SubscriptionWalletLedgerUpsertBulk) AddDeltaUsd(v float64) *SubscriptionWalletLedgerUpsertBulk {
	return u.Update(func(s *SubscriptionWalletLedgerUpsert) {
		s.AddDeltaUsd(v)
	})
}

// UpdateDeltaUsd sets the "delta_usd" field to the value that was provided on create.
func (u *SubscriptionWalletLedgerUpsertBulk) UpdateDeltaUsd() *SubscriptionWalletLedgerUpsertBulk {
	return u.Update(func(s *SubscriptionWalletLedgerUpsert) {
		s.UpdateDeltaUsd()
	})
}

// SetBalanceAfter sets the "balance_after" field.
func (u *SubscriptionWalletLedgerUpsertBulk) SetBalanceAfter(v float64) *SubscriptionWalletLedgerUpsertBulk {
	return u.Update(func(s *SubscriptionWalletLedgerUpsert) {
		s.SetBalanceAfter(v)
	})
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *SubscriptionWalletLedgerUpsertBulk) AddBalanceAfter(v float64) *SubscriptionWalletLedgerUpsertBulk {
	return u.Update(func(s *SubscriptionWalletLedgerUpsert) {
		s.AddBalanceAfter(v)
	})
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *SubscriptionWalletLedgerUpsertBulk) UpdateBalanceAfter() *SubscriptionWalletLedgerUpsertBulk {
	return u.Update(func(s *SubscriptionWalletLedgerUpsert) {
		s.UpdateBalanceAfter()
	})
}

// SetReason sets the "reason" field.
func (u *SubscriptionWalletLedgerUpsertBulk) SetReason(v string) *SubscriptionWalletLedgerUpsertBulk {
	return u.Update(func(s *SubscriptionWalletLedgerUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *SubscriptionWalletLedgerUpsertBulk) UpdateReason() *SubscriptionWalletLedgerUpsertBulk {
	return u.Update(func(s *SubscriptionWalletLedgerUpsert) {
		s.UpdateReason()
	})
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *SubscriptionWalletLedgerUpsertBulk) SetUsageLogID(v int64) *SubscriptionWalletLedgerUpsertBulk {
	return u.Update(func(s *SubscriptionWalletLedgerUpsert) {
		s.SetUsageLogID(v)
	})
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *SubscriptionWalletLedgerUpsertBulk) UpdateUsageLogID() *SubscriptionWalletLedgerUpsertBulk {
	return u.Update(func(s *SubscriptionWalletLedgerUpsert) {
		s.UpdateUsageLogID()
	})
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (u *SubscriptionWalletLedgerUpsertBulk) ClearUsageLogID() *SubscriptionWalletLedgerUpsertBulk {
	return u.Update(func(s *SubscriptionWalletLedgerUpsert) {
		s.ClearUsageLogID()
	})
}

// SetOperatorID sets the "operator_id" field.
func (u *SubscriptionWalletLedgerUpsertBulk) SetOperatorID(v int64) *SubscriptionWalletLedgerUpsertBulk {
	return u.Update(func(s *SubscriptionWalletLedgerUpsert) {
		s.SetOperatorID(v)
	})
}

// UpdateOperatorID sets the "operator_id" field to the value that was provided on create.
func (u *SubscriptionWalletLedgerUpsertBulk) UpdateOperatorID() *SubscriptionWalletLedgerUpsertBulk {
	return u.Update(func(s *SubscriptionWalletLedgerUpsert) {
		s.UpdateOperatorID()
	})
}

// ClearOperatorID clears the value of the "operator_id" field.
func (u *SubscriptionWalletLedgerUpsertBulk) ClearOperatorID() *SubscriptionWalletLedgerUpsertBulk {
	return u.Update(func(s *SubscriptionWalletLedgerUpsert) {
		s.ClearOperatorID()
	})
}

// SetNotes sets the "notes" field.
func (u *SubscriptionWalletLedgerUpsertBulk) SetNotes(v string) *SubscriptionWalletLedgerUpsertBulk {
	return u.Update(func(s *SubscriptionWalletLedgerUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *SubscriptionWalletLedgerUpsertBulk) UpdateNotes() *SubscriptionWalletLedgerUpsertBulk {
	return u.Update(func(s *SubscriptionWalletLedgerUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *SubscriptionWalletLedgerUpsertBulk) ClearNotes() *SubscriptionWalletLedgerUpsertBulk {
	return u.Update(func(s *SubscriptionWalletLedgerUpsert) {
		s.ClearNotes()
	})
}

// Exec executes the query.
func (u *SubscriptionWalletLedgerUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SubscriptionWalletLedgerCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionWalletLedgerCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionWalletLedgerUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
