package repository

import (
	"strings"
	"testing"

	"github.com/Wei-Shaw/sub2api/internal/config"
	"github.com/Wei-Shaw/sub2api/internal/service"
	"github.com/stretchr/testify/require"
)

func TestNewAESEncryptorRejectsAutoGeneratedEphemeralKey(t *testing.T) {
	cfg := domainKeyTestConfig()
	cfg.SecretEncryption.ContentModerationKey = ""
	_, err := NewAESEncryptor(cfg)
	require.Error(t, err)
	require.Contains(t, err.Error(), "SECRET_ENCRYPTION_CONTENT_MODERATION_KEY")
}

func TestNewAESEncryptorRejectsMissingProxyCredentialKey(t *testing.T) {
	cfg := domainKeyTestConfig()
	cfg.SecretEncryption.ProxyCredentialKey = ""

	_, err := NewAESEncryptor(cfg)

	require.Error(t, err)
	require.Contains(t, err.Error(), "SECRET_ENCRYPTION_PROXY_CREDENTIAL_KEY")
}

func TestNewAESEncryptorRejectsMissingSchedulerCacheKey(t *testing.T) {
	cfg := domainKeyTestConfig()
	cfg.SecretEncryption.SchedulerCacheKey = ""

	_, err := NewAESEncryptor(cfg)

	require.Error(t, err)
	require.Contains(t, err.Error(), "SECRET_ENCRYPTION_SCHEDULER_CACHE_KEY")
}

func TestNewAESEncryptorRejectsMissingOAuthTokenCacheKey(t *testing.T) {
	cfg := domainKeyTestConfig()
	cfg.SecretEncryption.OAuthTokenCacheKey = ""

	_, err := NewAESEncryptor(cfg)

	require.Error(t, err)
	require.Contains(t, err.Error(), "SECRET_ENCRYPTION_OAUTH_TOKEN_CACHE_KEY")
}

func TestNewAESEncryptorRejectsMissingJWTHMACKey(t *testing.T) {
	cfg := domainKeyTestConfig()
	cfg.SecretEncryption.JWTHMACKey = ""

	_, err := NewAESEncryptor(cfg)

	require.Error(t, err)
	require.Contains(t, err.Error(), "SECRET_ENCRYPTION_JWT_HMAC_KEY")
}

func TestNewAESEncryptorRejectsMissingSettingSecretKey(t *testing.T) {
	cfg := domainKeyTestConfig()
	cfg.SecretEncryption.SettingSecretKey = ""

	_, err := NewAESEncryptor(cfg)

	require.Error(t, err)
	require.Contains(t, err.Error(), "SECRET_ENCRYPTION_SETTING_SECRET_KEY")
}

func TestNewAESEncryptorRejectsJWTHMACRootReusedAsSigningSecret(t *testing.T) {
	cfg := domainKeyTestConfig()
	cfg.JWT.Secret = cfg.SecretEncryption.JWTHMACKey

	_, err := NewAESEncryptor(cfg)

	require.Error(t, err)
	require.Contains(t, err.Error(), "distinct from JWT_SECRET")
}

func TestNewAESEncryptorRejectsReusedOAuthTokenCacheKey(t *testing.T) {
	cfg := domainKeyTestConfig()
	cfg.SecretEncryption.OAuthTokenCacheKey = cfg.SecretEncryption.SchedulerCacheKey

	_, err := NewAESEncryptor(cfg)

	require.Error(t, err)
	require.Contains(t, err.Error(), service.SecretDomainOAuthTokenCache)
	require.Contains(t, err.Error(), service.SecretDomainSchedulerCache)
}

func TestNewAESEncryptorUsesExplicitStableKeyAcrossInstances(t *testing.T) {
	cfg := domainKeyTestConfig()
	first, err := NewAESEncryptor(cfg)
	require.NoError(t, err)
	second, err := NewAESEncryptor(cfg)
	require.NoError(t, err)

	ciphertext, err := first.Encrypt("persistent-secret")
	require.NoError(t, err)
	plaintext, err := second.Decrypt(ciphertext)
	require.NoError(t, err)
	require.Equal(t, "persistent-secret", plaintext)
}

func TestAESEncryptorBindsCiphertextToSecretDomain(t *testing.T) {
	cfg := domainKeyTestConfig()
	firstRaw, err := NewAESEncryptor(cfg)
	require.NoError(t, err)
	secondRaw, err := NewAESEncryptor(cfg)
	require.NoError(t, err)
	first := firstRaw.(*AESEncryptor)
	second := secondRaw.(*AESEncryptor)

	ciphertext, err := first.EncryptForDomain(service.SecretDomainTOTP, "domain-secret")
	require.NoError(t, err)
	require.True(t, strings.HasPrefix(ciphertext, secretDomainCiphertextPrefix))

	plaintext, err := second.DecryptForDomain(service.SecretDomainTOTP, ciphertext)
	require.NoError(t, err)
	require.Equal(t, "domain-secret", plaintext)

	_, err = second.DecryptForDomain(service.SecretDomainContentModeration, ciphertext)
	require.Error(t, err)
	_, err = second.Decrypt(ciphertext)
	require.Error(t, err)
}

func TestNewAESEncryptorRejectsReusedDomainRoots(t *testing.T) {
	cfg := domainKeyTestConfig()
	cfg.SecretEncryption.BackupS3Key = cfg.SecretEncryption.AccountCredentialKey

	_, err := NewAESEncryptor(cfg)
	require.Error(t, err)
	require.Contains(t, err.Error(), "must be distinct")
}

func TestNewAESEncryptorRejectsDomainRootReusedFromLegacyRoot(t *testing.T) {
	cfg := domainKeyTestConfig()
	cfg.SecretEncryption.TOTPSecretKey = cfg.Totp.EncryptionKey

	_, err := NewAESEncryptor(cfg)
	require.Error(t, err)
	require.Contains(t, err.Error(), "TOTP_ENCRYPTION_KEY")
}

func TestAESEncryptorDomainRootsAreIndependentlyReplaceable(t *testing.T) {
	firstConfig := domainKeyTestConfig()
	secondConfig := domainKeyTestConfig()
	secondConfig.SecretEncryption.ContentModerationKey = strings.Repeat("e", 64)

	firstRaw, err := NewAESEncryptor(firstConfig)
	require.NoError(t, err)
	secondRaw, err := NewAESEncryptor(secondConfig)
	require.NoError(t, err)
	first := firstRaw.(service.DomainSecretEncryptor)
	second := secondRaw.(service.DomainSecretEncryptor)

	totpCiphertext, err := first.EncryptForDomain(service.SecretDomainTOTP, "totp-value")
	require.NoError(t, err)
	moderationCiphertext, err := first.EncryptForDomain(service.SecretDomainContentModeration, "moderation-value")
	require.NoError(t, err)

	got, err := second.DecryptForDomain(service.SecretDomainTOTP, totpCiphertext)
	require.NoError(t, err)
	require.Equal(t, "totp-value", got)
	_, err = second.DecryptForDomain(service.SecretDomainContentModeration, moderationCiphertext)
	require.Error(t, err)
}

func TestAESEncryptorAllowsLegacyRootRetirementAfterV3Cutover(t *testing.T) {
	cfg := domainKeyTestConfig()
	cfg.Totp.EncryptionKey = ""
	cfg.Totp.EncryptionKeyConfigured = false

	raw, err := NewAESEncryptor(cfg)
	require.NoError(t, err)
	encryptor := raw.(service.DomainSecretEncryptor)
	ciphertext, err := encryptor.EncryptForDomain(service.SecretDomainTOTP, "v3-only")
	require.NoError(t, err)
	plaintext, err := encryptor.DecryptForDomain(service.SecretDomainTOTP, ciphertext)
	require.NoError(t, err)
	require.Equal(t, "v3-only", plaintext)
	_, err = raw.Decrypt("legacy-ciphertext")
	require.ErrorContains(t, err, "legacy TOTP_ENCRYPTION_KEY is unavailable")
}

func domainKeyTestConfig() *config.Config {
	return &config.Config{
		Totp: config.TotpConfig{
			EncryptionKey:           strings.Repeat("a", 64),
			EncryptionKeyConfigured: true,
		},
		SecretEncryption: config.SecretEncryptionConfig{
			TOTPSecretKey:        strings.Repeat("1", 64),
			TOTPCacheKey:         strings.Repeat("2", 64),
			AccountCredentialKey: strings.Repeat("3", 64),
			BackupS3Key:          strings.Repeat("4", 64),
			ContentModerationKey: strings.Repeat("5", 64),
			ChannelMonitorKey:    strings.Repeat("6", 64),
			PaymentProviderKey:   strings.Repeat("7", 64),
			ProxyCredentialKey:   strings.Repeat("8", 64),
			SchedulerCacheKey:    strings.Repeat("9", 64),
			OAuthTokenCacheKey:   strings.Repeat("b", 64),
			JWTHMACKey:           strings.Repeat("c", 64),
			SettingSecretKey:     strings.Repeat("d", 64),
		},
	}
}
